apiVersion: v1
kind: Secret
metadata:
  name: airbyte-basic-auth
  namespace: airbyte
type: Opaque
data:
  .htpasswd: ${BASIC_AUTH_FILE_BASE64} # gerado na maquina e incluid no secrets do github
                                        #leia readme.md
